# Generated by Django 5.1.5 on 2025-01-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.discount'),
        ),
    ]
